# Generated by Django 4.1.2 on 2023-06-13 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='censo',
            fields=[
                ('idCenso', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField(verbose_name='Anio Censo')),
            ],
        ),
        migrations.CreateModel(
            name='detalleEstadisticoDiscapacitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadHombre', models.IntegerField()),
                ('cantidadMujeres', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tipoDiscapacidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre Discapacidad')),
                ('censo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.censo')),
                ('detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.detalleestadisticodiscapacitado')),
            ],
        ),
        migrations.CreateModel(
            name='sectorEconomico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre Sector')),
                ('censo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.censo')),
                ('detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.detalleestadisticodiscapacitado')),
            ],
        ),
        migrations.CreateModel(
            name='rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre Rubro')),
                ('censo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.censo')),
                ('detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.detalleestadisticodiscapacitado')),
            ],
        ),
        migrations.CreateModel(
            name='rangoEdades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=5, verbose_name='Rango Edad')),
                ('censo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.censo')),
                ('detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.detalleestadisticodiscapacitado')),
            ],
        ),
        migrations.CreateModel(
            name='categoriaOcupacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre Categoria')),
                ('censo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.censo')),
                ('detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.detalleestadisticodiscapacitado')),
            ],
        ),
    ]
